baseURL: '/'
title: Test processing order
theme: trial-repo-processing-order

params:
  # scratchProcessing: # home / layouts / customLayout
  # Process the partial for adding some Scratch data to a page:
  #   home - for each page in a loop in home layout (`/index.html)
  #   layouts - as the page is processed by the corresponding layout
  #   customLayout - for each page in a loop in custom layout (`_default/custom-layout.html)
  scratchProcessing: customLayout

outputs:
  home:
  - HTML
  - custom-output

outputFormats:
  custom-output:
    baseName: custom-output
    mediaType: text/html